### ISSUE TITLE
Renaming parts of partitioned DAGs

### ISSUE THREAD

**Issue by matthiasdiener** [inducer/arraycontext#260]
Currently, kernels of partitioned DAGs all have the same name. It would be helpful for debugging to have different names for each part.

**Comment by inducer** [comment]
This is a semi-simple endeavor. In principle, `_prg_id_to_kernel_name` just needs to be taught to do the right thing:

https://github.com/inducer/arraycontext/blob/146c598c688b519eb4cc6be5966a56e2a6e6292e/arraycontext/impl/pytato/compile.py#L59-L67

Grudge even passes an appropriate program ID:

https://github.com/inducer/grudge/blob/c2be52350a0fc3a6d1c6d3a6972fb374ff23dbd2/grudge/array_context.py#L170-L183

But we can't really in good conscience let `_prg_id_to_kernel_name` in arraycontext be aware of that class. The better idea (IMO) would be to move distributed-memory-awareness from arraycontexts in grudge into arraycontext proper.

**Comment by matthiasdiener** [comment]
Thanks for the pointers @inducer! I think the functionality is already there, but there is an issue with the identifier conversion in grudge (see https://github.com/inducer/grudge/pull/341).
