### ISSUE TITLE
Provide a default implementation for `transform_loopy_program`

### ISSUE THREAD

**Issue by inducer** [inducer/arraycontext#272]
@nkoskelo points out that the first-time user experience kind of stinks otherwise.

This should still issue a warning to emphasize that things won't perform without additional transformation.

**Comment by alexfikl** [comment]
Is this in the `pytato` array context or..?

**Comment by inducer** [comment]
Generally. (Since all actxs provide `call_loopy`.)

**Comment by inducer** [comment]
You're right! It's just pytato. I was wrong. It's deprecated in the PyOpenCL one, but I'll just un-deprecate it.
